# Generated by Django 5.1.6 on 2025-03-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='자기소개, 요약 등', null=True)),
                ('content', models.TextField(blank=True, help_text='경력, 프로젝트, 경험 등의 상세 내용', null=True)),
                ('slug', models.SlugField(blank=True, help_text='이력서 공유를 위한 고유 식별자', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: C, C++, C#, .NET, Linux, Unix, Python, Ruby, R 등', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="포트폴리오 항목의 이름 (예: 'GitHub', '출시 프로젝트')", max_length=255)),
                ('url', models.URLField(help_text='포트폴리오 URL (예: GitHub, 블로그, 유튜브 링크 등)')),
                ('description', models.TextField(blank=True, help_text="포트폴리오에 대한 간단한 설명 (예: '이 프로젝트는 역량 중심 이력서 작성 및 관리 웹 사이트입니다.')", null=True)),
                ('resume', models.ForeignKey(help_text='연결된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='resume_api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 백엔드 개발자 이력서, 프론트엔드 개발자 이력서 등', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='이력서 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='resume_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_list',
            field=models.ForeignKey(help_text='이력서 목록에 포함된 이력서', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resume_api.resumelist'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, help_text='해당 이력서에 포함할 기술 스택', related_name='resumes', to='resume_api.technologystack'),
        ),
    ]
