# Generated by Django 5.1.6 on 2025-04-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_list',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tech_stacks',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='slug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='포트폴리오 제목', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolios',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resume_api.portfolio'),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='이력서 제목', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resume_api.skill'),
        ),
        migrations.DeleteModel(
            name='ResumeList',
        ),
        migrations.DeleteModel(
            name='TechnologyStack',
        ),
    ]
